[package]
name = "zr"
version = "0.6.5"
authors = ["Jonathan Dahan <hi@jonathan.is>"]
description = "quick, simple zsh package manager"
readme = "readme.md"
keywords = ["zsh", "package", "manager", "cli"]
license = "MPL-2.0"
repository = "https://github.com/jedahan/zr.git"

[badges]
travis-ci = { repository = "jedahan/zr" }

[dependencies]
clap = "2.29"
git2 = "0.6"
libc = "0.2"

[features]
default = []

[lib]
name = "libzr"
path = "src/lib.rs"

[[bin]]
name = "zr"
path = "src/main.rs"
