[package]
name = "zr"
version = "0.4.2"
authors = ["Jonathan Dahan <hi@jonathan.is>"]

[dependencies]
clap = "~2"
git2 = "~0.6.5"
libc = "~0.2.22"
clippy = {version = "*", optional = true}

[features]
default = []
