[package]
name = "zr"
version = "0.7.0"
authors = ["Jonathan Dahan <hi@jonathan.is>"]
description = "quick, simple zsh package manager"
readme = "readme.md"
keywords = ["zsh", "packge", "manager", "cli"]
license = "MPL-2.0"

[badges]
travis-ci = { repository = "jedahan/zr" }

[dependencies]
clap = "~2"
git2 = "~0.6.5"
libc = "~0.2.22"
url = "~1.5.1"
clippy = {version = "*", optional = true}

[features]
default = []

[lib]
name = "libzr"
path = "src/lib.rs"

[[bin]]
name = "zr"
path = "src/main.rs"
