name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: cargo build --verbose
    - name: test
      run: cargo test --verbose
    - name: extend
      run: |
        cargo install cargo-bloat
        cargo install cargo-geiger
        cargo install cargo-audit
        cargo install tokei
    - name: size
      run: cargo bloat --release --crates

    - name: geiger
      run: cargo geiger

    - name: audit
      run: cargo audit

    - name: count
      run: tokei
